### ISSUE TITLE
CLI Book: Rust Version Typo

### ISSUE THREAD

**Issue by sansbrina** [rust-lang-nursery/cli-wg#103]
I'm just working through this book now and noticed what I think is a version typo.
I didn't find any related issues and am brand new to Rust, so I'm hoping I'm not off base with these.

[The first chapter](https://rust-lang-nursery.github.io/cli-wg/tutorial/index.html) states 
> Make sure you run Rust 1.31.0 (or later) 

but looking at the [blog](https://blog.rust-lang.org/) and other language resources, the most recent version appears to be Rust 1.30.1.

Really enjoying the book so far, it's exactly what I was looking for!

**Comment by killercup** [comment]
Wait just a few more hours ;)

**Comment by killercup** [comment]
Or not even half an hour! 🎉 https://twitter.com/rustlang/status/1070732843855294467

> I didn't find any related issues and am brand new to Rust, so I'm hoping I'm not off base with these.

No worries! I really appreciate that you took the time to open an issue here.

To give a bit more context: The book ws written to be used with latest Rust version, as it gives us a few very convenient features, that make the code examples more approachable. This release was scheduled for today, and I hoped most people would first find the book at a time where 1.31 was already available. You were just an hour early for my plan to work :)

If you want to know more about this version, and why it is a pretty big deal, check out [this post](https://hacks.mozilla.org/2018/12/rust-2018-is-here/).

> Really enjoying the book so far, it's exactly what I was looking for!

I'm so glad to hear it! That means a lot to me! <3

If you have any questions, found errors, or have suggestions, please let me know! You are welcome to open more issues, ping me on IRC or discord, or just write me an email.

Since you said you are new to Rust, I'm especially interested in the parts where you needed to look up stuff that were not mentioned anywhere – I tried to link to some of the chapters of the "Rust book", but I'm sure there's a lot of room for improvement.
