### ISSUE TITLE
First draft of CLI website

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#46]
cf. #45 for general idea

Let's get a website up and running, with some drafts for content, but no need to have anything ready and polished.

### Decide

- [x] How to implement this? mdbook? Jekyll?
- [x] First content

**Comment by Aaronepower** [comment]
I believe it should probably be a similar setup as the WebAssembly working group with both a jekyll site and mdbook. As mdbook is not a good landing page, and there needs to be a way to show other content such as the newsletter or anything else we want to publish.

**Comment by killercup** [comment]
I'd try to avoid using more than one tool. I don't think we have the
bandwidth to publish regular blog posts or a newsletter for once. We can
try to publish sections of a "book" (think: short guides, summaries of
interesting crates, etc.) in their place, too. These can also be updated
regularly---which is as much blessing as it is curse (people will expect
this to be up to date).

But: Part of creating a theme for mdbook would include a very customized
start page! Any ideas? :)

**Comment by deg4uss3r** [comment]
Definitely something that looks like a terminal matrix style :P

**Comment by tvannahl** [comment]
To be a book that includes best practises and pattern does sound very desirable. For later consultations a good overview about what changed (dropped pattern, etc.) would also be really nice.

Personally I do prefer a book since its easier and faster to comprehend the structure of it and straight forward to use as a lookup source.


# Content to cover

To be more precise on the content I would assume on a cli-wg book to have:

 * An introduction about the problem (cli) covered by the book.
 * Introduction into CLI parsing using `clap` and reference to 5(?) popular alternatives one could look into.
 * Introduction about the Signal handling problem (see #12, #27) and recommendation of a solution.
 * Introduction about man page generation
 * Introduction into config file management (#7) and config file parsing.
 * Exit codes (`sysexits.h`, `errno(3)` from #39) does sound like a good praxis, too.


# Referenced content

If such a book is meant to be an introduction about developing a cli application, there are topics I would not cover but only reference. *Further read* if you will.

As such further read topic I would assume the following topics to fit right into this:

 * #8 (Packaging and distributing apps)
 * #9 (Testing CLI apps)


# Possibly to consider

I don't know much about the cross-platform problem (#10) but since the related thread is rather active I assume it has relevance for cli as well.

**Comment by killercup** [comment]
Thanks, @tvannahl! I've updated #47 with a draft of a book structure. This is very much not set in stone -- I'd love some feedback!

**Comment by killercup** [comment]
This is now live at https://rust-lang-nursery.github.io/cli-wg/

I'll close this "first draft" issue and will open new ones if necessary, but will try to keep general content discussions in #45.
